"""Add summary column to documents

Revision ID: 0b8411e51477
Revises: 61f53b8a57ac
Create Date: 2026-07-16 21:18:16.004140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8411e51477'
down_revision: Union[str, Sequence[str], None] = '61f53b8a57ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.JSON(), nullable=True))
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
