"""Add summary  paths

Revision ID: 19c9f85a5893
Revises: 0b8411e51477
Create Date: 2026-07-16 21:31:46.770274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c9f85a5893'
down_revision: Union[str, Sequence[str], None] = '0b8411e51477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary_file_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('summary_file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary_file_name')
    op.drop_column('documents', 'summary_file_path')
    # ### end Alembic commands ###
