"""add page nbr to doc chunk

Revision ID: 877a94ae9edb
Revises: f7a36d5257d1
Create Date: 2026-07-13 01:37:18.806036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877a94ae9edb'
down_revision: Union[str, Sequence[str], None] = 'f7a36d5257d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
